version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:8.11.4
    working_directory: ~/repo
    resource_class: small

commands:
  docker_layer_caching:
    description: "Setup Docker layer caching"
    steps:
      - setup_remote_docker: #enable docker command
          version: 18.06.0-ce
          docker_layer_caching: true


jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - docker_layer_caching

      - run:
          name: Build and Tag Production Image
          command: docker build -t countdown-client .

      - run:
          name: Create junit result directory
          command: mkdir -p ~/junit

      - run:
          name: run service unit tests
          command: docker run --init --tty countdown-client

      - run:
          name: copy test results
          command: docker cp $(docker ps -a -l -q):/results/results.xml ~/junit/test-results.xml
          when: always

      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
